### ISSUE TITLE
Convert .x_t files to .png files

### ISSUE THREAD

**Issue by Spoutnik97** [deGravity/breploader#2]
Hi @deGravity ,
is it possible to convert .x_t files to .png or .step files with your program ? I don't find the documentation :)

**Comment by deGravity** [comment]
No, that's not what this is for. This code is a wrapper library for both Parasolid and OpenCascade to give them a common interface for reading B-Rep models (x_t and step), it does not do any writing or converting.

I have yet to find an open solution for converting x_t to step, but have had some success with CADExchanger is the past (and last time I looked they do have a free trial).

**Comment by deGravity** [comment]
Closing as not in scope.
